### ISSUE TITLE
picture-store-keeper-backend が作成された際にwindowsでは実行できない

### ISSUE THREAD

**Issue by Jade-Laurent** [WL-Amigo/PictureStoreKeeper#21]
# 事象
readme 46行目の `build.sh` を実行した際に、作成される `picture-store-keeper-backend`に拡張子がないため、実行ができない
# 再現方法
'build.sh' を実行した後に `build-release/picture-store-keeper-backend` を確認する。
# 環境
win10

# 回避方法
ファイル名を書き換え、 `.exe`拡張子を書き足す

**Comment by WL-Amigo** [comment]
#28 (#34) にて、ビルド時ターゲットOSが Windows だった場合に拡張子を付与するように設定済みです。
